### ISSUE TITLE
Command line arguments for username and password not supported

### ISSUE THREAD

**Issue by EvgeniGordeev** [jutzig/github-release-plugin#12]
It's impossible to provide scm username and password in command line like
``` 
mvn github-release:release -Dusername=myUserName -Dpassword=myPassword
 ```
Plugin depends on the settings file what might be a tedious task to provide a separate one in CI environment.

**Comment by jutzig** [comment]
You can put properties instead of actual credentials in your settings.xml and then provide those properties as system properties. With other plugins like maven-wagon it's usually done the same way.

**Comment by EvgeniGordeev** [comment]
Yes, there might be workarounds like this. But you still don't want to hold in repository any environment specific files.

**Comment by EvgeniGordeev** [comment]
Compare with maven-release-plugin which allows:
```
release:perform --batch-mode -Dusername=${scm.username} -Dpassword=${scm.password}
```

**Comment by EvgeniGordeev** [comment]
Do you plan to make a new release with this issue?

**Comment by jutzig** [comment]
Yes, release 1.1.1 just passed staging and should be available on central
