### ISSUE TITLE
Enable Overwriting Releases

### ISSUE THREAD

**Issue by norswap** [jutzig/github-release-plugin#28]
This would be handy for snapshot releases: I want to always have a release that says e.g. `1.0-SNAPSHOT` (replace 1.0 with the current version).

This is in-line with how maven treats `SNAPSHOT` as artifact that will change.

Currently you can update artifacts, but not the commit the release is based on.

Current workaround:
- manually delete the previous release on GitHub.
- `git tag -d 1.0-SNAPSHOT`
- `git push origin :refs/tags/1.0-SNAPSHOT`
- re-release

**Comment by norswap** [comment]
Okay, I didn't know what draft releases where (untagged releases), and they actually solve my problem perfectly.

May I suggest instead to enable having two configurations of the plugin: one for drafts and one for "real" releases. Maybe through multiple `executions`? This would avoid changing the `draft` flag in `pom.xml` each time I want to do a real release. It's only a small thing though.

**Comment by norswap** [comment]
Turns out Jitpack allows to build from the last commit.
It just wasn't working because (1) a maven plugin I was using had its deployment to maven central shot a few days ago, (2) jitpack's cache weren't updated in the meantime.

I still think overwriting releases would be nice, for users that are not using Maven and simply download the jars. I can appreciate that moving a tag around is not super clean, but it doesn't seem dangerous like history rewriting, and the way things are set up, Github doesn't leave any other choice.

**Comment by carlspring** [comment]
Hi,

Has there been any progress on this?

It works and it uploads the artifact, but it doesn't seem to be updating the date.

**Comment by carlspring** [comment]
Could you please add an option to delete releases, instead of deleting just the files for these releases?

**Comment by carlspring** [comment]
I have raised #38. Could you please review and merge it?
